name: Example
on: [push]
jobs:
  setupv1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v1
        with:
          go-version: "1.19.1"
      - name: Install and Run Command
        env:
          GOBIN: ${{env.GOROOT}}/bin
        run: |
          echo "GOROOT is ${GOROOT}"
          go install
          setup-go-example
  setupv3:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
      - name: Install and Run Command
        env:
          GOBIN: ${{env.GOROOT}}/bin
        run: |
          echo "GOROOT is ${GOROOT}"
          go install
          setup-go-example
